name: /home/jovyan/data/conda-envs/firewaterenv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - affine=2.3.0=py_0
  - appdirs=1.4.3=py_1
  - argon2-cffi=20.1.0=py36h8c4c3a4_1
  - asciitree=0.3.3=py_2
  - attrs=20.1.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - beautifulsoup4=4.9.1=py_1
  - black=19.10b0=py_4
  - bleach=3.1.5=pyh9f0ad1d_0
  - blosc=1.20.0=he1b5a44_0
  - bmipy=2.0=py_0
  - bokeh=2.2.0=py36h9f0ad1d_0
  - boost-cpp=1.72.0=h8e57a91_0
  - boto3=1.14.50=pyh9f0ad1d_0
  - botocore=1.17.50=pyh9f0ad1d_0
  - branca=0.4.1=py_0
  - brotlipy=0.7.0=py36h8c4c3a4_1000
  - bzip2=1.0.8=h516909a_3
  - c-ares=1.16.1=h516909a_3
  - ca-certificates=2020.6.20=hecda079_0
  - cachetools=4.1.1=py_0
  - cairo=1.16.0=hcf35c78_1003
  - cartopy=0.18.0=py36hd60729c_0
  - certifi=2020.6.20=py36h9f0ad1d_0
  - cffi=1.14.1=py36h0ff685e_0
  - cfitsio=3.470=hce51eda_6
  - cftime=1.2.1=py36h785e9b2_0
  - chardet=3.0.4=py36h9f0ad1d_1006
  - click=7.1.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - cloudpickle=1.6.0=py_0
  - colorcet=2.0.1=py_0
  - contextily=1.0.0=py_0
  - contextvars=2.4=py_0
  - cryptography=3.1=py36h45558ae_0
  - curl=7.71.1=he644dc0_5
  - cycler=0.10.0=py_2
  - cytoolz=0.10.1=py36h516909a_0
  - dask=2.24.0=py_0
  - dask-core=2.24.0=py_0
  - dataclasses=0.7=py36_0
  - datashader=0.11.1=pyh9f0ad1d_0
  - datashape=0.5.4=py_1
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - descartes=1.1.0=py_4
  - distributed=2.24.0=py36h9f0ad1d_0
  - docutils=0.15.2=py36_0
  - earthengine-api=0.1.233=pyh9f0ad1d_0
  - entrypoints=0.3=py36h9f0ad1d_1001
  - expat=2.2.9=he1b5a44_2
  - fasteners=0.14.1=py_3
  - fiona=1.8.13=py36h70cb5cc_1
  - folium=0.11.0=py_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.2=he06d7ca_0
  - freexl=1.0.5=h516909a_1002
  - freezegun=0.3.15=py_0
  - fsspec=0.8.0=py_0
  - future=0.18.2=py36h9f0ad1d_1
  - gdal=3.0.4=py36hd60729c_10
  - geographiclib=1.50=py_0
  - geojson=2.5.0=py_0
  - geopandas=0.8.1=py_0
  - geopy=2.0.0=pyh9f0ad1d_0
  - geos=3.8.1=he1b5a44_0
  - geotiff=1.6.0=h05acad5_0
  - geoviews=1.8.1=py_0
  - geoviews-core=1.8.1=py_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.2.1=h516909a_2
  - glib=2.65.0=h6f030ca_0
  - google-api-core=1.22.1=py36h9f0ad1d_0
  - google-api-python-client=1.11.0=pyh9f0ad1d_0
  - google-auth=1.21.0=py_0
  - google-auth-httplib2=0.0.3=py_3
  - google-cloud-core=1.4.1=pyh9f0ad1d_0
  - google-cloud-storage=1.31.0=pyh9f0ad1d_0
  - google-crc32c=1.0.0=py36h9c36872_0
  - google-resumable-media=1.0.0=pyh9f0ad1d_0
  - googleapis-common-protos=1.51.0=py36h9f0ad1d_2
  - grpcio=1.31.0=py36h769ab6c_0
  - hdf4=4.2.13=hf30be14_1003
  - hdf5=1.10.6=nompi_h3c11f04_101
  - heapdict=1.0.1=py_0
  - holoviews=1.13.3=pyh9f0ad1d_0
  - html5lib=0.9999999=py36_0
  - httplib2=0.18.1=pyh9f0ad1d_0
  - hvplot=0.6.0=pyh9f0ad1d_0
  - hydrodata=0.7.2=py_0
  - icu=64.2=he1b5a44_1
  - idna=2.10=pyh9f0ad1d_0
  - immutables=0.14=py36h8c4c3a4_0
  - importlib-metadata=1.7.0=py36h9f0ad1d_0
  - importlib_metadata=1.7.0=0
  - iniconfig=1.0.1=pyh9f0ad1d_0
  - intake=0.6.0=py_0
  - ipykernel=5.3.4=py36h95af2a2_0
  - ipython=5.8.0=py36_1
  - ipython_genutils=0.2.0=py_1
  - isodate=0.6.0=py_1
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - joblib=0.16.0=py_0
  - jpeg=9d=h516909a_0
  - json-c=0.13.1=hbfbb72e_1002
  - jsonschema=3.2.0=py36h9f0ad1d_1
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.6.3=py36h9f0ad1d_1
  - kealib=1.4.13=h33137a7_1
  - kiwisolver=1.2.0=py36hdb11119_0
  - krb5=1.17.1=hfafb76e_2
  - landlab=2.2.0=py36h68bb277_0
  - lcms2=2.11=hbd6801e_0
  - ld_impl_linux-64=2.34=hc38a660_9
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libcrc32c=1.1.1=he1b5a44_2
  - libcurl=7.71.1=hcdd3856_5
  - libdap4=3.20.6=h1d1bd15_1
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_0
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.3.0=h24d8f2e_16
  - libgdal=3.0.4=he6a97d6_10
  - libgfortran-ng=7.5.0=hdf63c60_16
  - libgomp=9.3.0=h24d8f2e_16
  - libiconv=1.16=h516909a_0
  - libkml=1.3.0=hb574062_1011
  - liblapack=3.8.0=17_openblas
  - libllvm10=10.0.1=he513fc3_3
  - libnetcdf=4.7.4=nompi_h84807e1_105
  - libnghttp2=1.41.0=h8cfc5f6_2
  - libopenblas=0.3.10=pthreads_hb3c22a3_4
  - libpng=1.6.37=hed695b0_2
  - libpq=12.3=h5513abc_0
  - libprotobuf=3.13.0=h8b12597_0
  - libsodium=1.0.18=h516909a_0
  - libspatialindex=1.9.3=he1b5a44_3
  - libspatialite=4.3.0a=h2482549_1038
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-ng=9.3.0=hdf63c60_16
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=hee79883_0
  - libxslt=1.1.33=h31b3aaa_0
  - llvmlite=0.34.0=py36hfa65bc7_1
  - locket=0.2.0=py_2
  - lxml=4.5.2=py36h17c4326_0
  - lz4-c=1.9.2=he1b5a44_3
  - lzo=2.10=h516909a_1000
  - markdown=3.2.2=py_0
  - markupsafe=1.1.1=py36h8c4c3a4_1
  - matplotlib=3.3.1=1
  - matplotlib-base=3.3.1=py36h5ffbc53_1
  - mercantile=1.1.6=pyh9f0ad1d_0
  - metpy=0.12.2=py_0
  - mistune=0.8.4=py36h8c4c3a4_1001
  - mock=4.0.2=py36h9f0ad1d_0
  - monotonic=1.5=py_0
  - more-itertools=8.4.0=py_0
  - msgpack-python=1.0.0=py36hdb11119_1
  - multipledispatch=0.6.0=py_0
  - munch=2.5.0=py_0
  - nb_conda_kernels=2.2.4=py36h9f0ad1d_0
  - nbconvert=5.6.1=py36h9f0ad1d_1
  - nbformat=5.0.7=py_0
  - ncurses=6.2=he1b5a44_1
  - netcdf4=1.5.4=nompi_py36ha8c3e71_102
  - networkx=2.5=py_0
  - notebook=6.1.3=py36h9f0ad1d_0
  - numba=0.51.1=py36h7c3b610_0
  - numcodecs=0.6.4=py36he1b5a44_0
  - numexpr=2.7.1=py36h830a2c2_1
  - numpy=1.19.1=py36h3849536_2
  - olefile=0.46=py_0
  - openjpeg=2.3.1=h981e76c_3
  - openssl=1.1.1g=h516909a_1
  - orjson=3.3.1=py36h8c4c3a4_0
  - owslib=0.20.0=py_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.0.5=py36h830a2c2_0
  - pandoc=2.10.1=h516909a_0
  - pandocfilters=1.4.2=py_1
  - panel=0.9.7=py_0
  - param=1.9.3=py_0
  - partd=1.1.0=py_0
  - pathspec=0.8.0=pyh9f0ad1d_0
  - patsy=0.5.1=py_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=py36h9f0ad1d_1
  - pickleshare=0.7.5=py36h9f0ad1d_1001
  - pillow=7.2.0=py36h8328e55_1
  - pint=0.15=py_0
  - pip=20.2.2=py_0
  - pixman=0.38.0=h516909a_1003
  - pluggy=0.13.1=py36h9f0ad1d_2
  - pooch=1.1.1=py_0
  - poppler=0.87.0=h4190859_1
  - poppler-data=0.4.9=1
  - postgresql=12.3=h8573dbc_0
  - proj=7.0.0=h966b41f_5
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt_toolkit=1.0.15=py_1
  - protobuf=3.13.0=py36h831f99a_0
  - psutil=5.7.2=py36h8c4c3a4_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - py=1.9.0=pyh9f0ad1d_0
  - py3dep=0.1.7=py_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyct=0.4.6=py_0
  - pyct-core=0.4.6=py_0
  - pydaymet=0.1.3=py_0
  - pyepsg=0.4.0=py_0
  - pygeoogc=0.1.10=py_0
  - pygeoutils=0.1.10=py_0
  - pygments=2.6.1=py_0
  - pynhd=0.1.3=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyproj=2.6.1.post1=py36he34cbb8_0
  - pyrsistent=0.16.0=py36h8c4c3a4_0
  - pyshp=2.1.0=py_0
  - pysocks=1.7.1=py36h9f0ad1d_1
  - pytables=3.6.1=py36h7b0bd57_2
  - pytest=6.0.1=py36h9f0ad1d_0
  - python=3.6.11=h4d41432_2_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytz=2020.1=pyh9f0ad1d_0
  - pyviz_comms=0.7.6=pyh9f0ad1d_0
  - pyyaml=5.3.1=py36h8c4c3a4_0
  - pyzmq=19.0.2=py36h9947dbf_0
  - rasterio=1.1.5=py36h70cb5cc_1
  - readline=8.0=he28a2e2_2
  - regex=2020.7.14=py36h8c4c3a4_0
  - regionmask=0.6.1=py_0
  - requests=2.24.0=pyh9f0ad1d_0
  - rioxarray=0.0.31=py_0
  - rsa=4.6=pyh9f0ad1d_0
  - rtree=0.9.4=py36he053a7a_1
  - s3fs=0.4.2=py_0
  - s3transfer=0.3.3=py36h9f0ad1d_1
  - scipy=1.5.2=py36h3a855aa_0
  - seaborn=0.10.1=1
  - seaborn-base=0.10.1=py_1
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py36h9f0ad1d_0
  - shapely=1.7.1=py36h15bcdef_0
  - simplegeneric=0.8.1=py_1
  - simplejson=3.17.2=py36h8c4c3a4_0
  - six=1.15.0=pyh9f0ad1d_0
  - snuggs=1.4.7=py_0
  - sortedcontainers=2.2.2=pyh9f0ad1d_0
  - soupsieve=2.0.1=py_1
  - sqlite=3.33.0=h4cf870e_0
  - statsmodels=0.12.0=py36h8c4c3a4_0
  - suds-jurko=0.6=py36h9f0ad1d_1003
  - tbb=2020.1=hc9558a2_0
  - tblib=1.6.0=py_0
  - terminado=0.8.3=py36h9f0ad1d_1
  - testpath=0.4.4=py_0
  - tiledb=1.7.7=h8efa9f0_3
  - tk=8.6.10=hed695b0_0
  - toml=0.10.1=pyh9f0ad1d_0
  - toolz=0.10.0=py_0
  - tornado=6.0.4=py36h8c4c3a4_1
  - tqdm=4.48.2=pyh9f0ad1d_0
  - traitlets=4.3.3=py36h9f0ad1d_1
  - typed-ast=1.4.1=py36h516909a_0
  - typing_extensions=3.7.4.2=py_0
  - tzcode=2020a=h516909a_0
  - ulmo=0.8.6=pyh9f0ad1d_0
  - uritemplate=3.0.1=py_0
  - urllib3=1.25.10=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_1
  - webencodings=0.5.1=py_1
  - wheel=0.35.1=pyh9f0ad1d_0
  - xarray=0.16.0=py_0
  - xerces-c=3.2.2=h8412b87_1004
  - xlrd=1.2.0=pyh9f0ad1d_1
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - zarr=2.4.0=py_0
  - zeromq=4.3.2=he1b5a44_3
  - zict=2.0.0=py_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h516909a_1007
  - zstd=1.4.5=h6597ccf_2
prefix: /home/jovyan/data/conda-envs/firewaterenv

